config/routes.rb
Rails.application.routes.draw do
  resources :orgs, except: :show do
    resources :events
  end

  root "orgs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :org

end

app/models/org.rb
class Org < ApplicationRecord

  has_many :events, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_org
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:create]

  # GET /events
  # GET /events.json
  def index
    @limit = params[:limit] || 50
    @hostname = params[:hostname]

    @events = @org.events.all.limit(@limit).order(timestamp: :desc)
    @events = @events.where(hostname: @hostname) if @hostname.present?
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = @org.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = @org.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to [@org, @event], notice: 'Event was successfully created.' }
        format.json { render :show, status: :created }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [@org, @event], notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to org_events_url(@org), notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = @org.events.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :timestamp, :hostname, :org_id)
    end

    def set_org
      @org = Org.find(params[:org_id])
    end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_action :set_org, only: [:show, :edit, :update, :destroy]

  # GET /orgs
  # GET /orgs.json
  def index
    @orgs = Org.all
  end

  # GET /orgs/1
  # GET /orgs/1.json
  def show
  end

  # GET /orgs/new
  def new
    @org = Org.new
  end

  # GET /orgs/1/edit
  def edit
  end

  # POST /orgs
  # POST /orgs.json
  def create
    @org = Org.new(org_params)

    if @org.save
      redirect_to orgs_path, notice: 'Org was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /orgs/1
  # PATCH/PUT /orgs/1.json
  def update
    if @org.update(org_params)
      redirect_to orgs_path, notice: 'Org was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orgs/1
  # DELETE /orgs/1.json
  def destroy
    @org.destroy
    redirect_to orgs_url, notice: 'Org was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_org
      @org = Org.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def org_params
      params.require(:org).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/views/events/_form.html.erb
<%= form_for([@org, event]) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :timestamp %>
    <%= f.datetime_select :timestamp %>
  </div>

  <div class="field">
    <%= f.label :hostname %>
    <%= f.text_field :hostname %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', [@org, @event] %> |
<%= link_to 'Back', org_events_path(@org) %>

app/views/events/index.html.erb
<h1>Events</h1>

<div style="background-color: #eee; padding: 20px;">
  <%= form_tag org_events_path(@org), method: :get do %>
    <div class="field">
      <label>
        Limit: <%= number_field_tag :limit, @limit %>
      </label>
    </div>

    <div class="field">
      <label>
        Hostname: <%= text_field_tag :hostname, @hostname %>
      </label>
    </div>

    <%= submit_tag "Search" %>
    &middot; <%= link_to "Reset", org_events_path(@org) %>
  <% end %>
</div>

<br>

<% if @events.present? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Timestamp</th>
        <th>Hostname</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.timestamp %></td>
          <td><%= event.hostname %></td>
          <td><%= link_to 'Show', [@org, event] %></td>
          <td><%= link_to 'Edit', edit_org_event_path(@org, event) %></td>
          <td><%= link_to 'Destroy', [@org, event], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>
    No events for this org.
  </p>
<% end %>

<br>

<%= link_to 'New Event', new_org_event_path(@org) %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', org_events_path(@org) %>

app/views/events/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @event.timestamp %>
</p>

<p>
  <strong>Hostname:</strong>
  <%= @event.hostname %>
</p>

<%= link_to 'Edit', edit_org_event_path(@org, @event) %> |
<%= link_to 'Back', org_events_path(@org) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>

    <% if @org.present? && @org.persisted? %>
      <%= link_to_unless_current "Orgs", orgs_path %> ›
      <%= truncate(@org.name) %>
      <% if @event.present? && @event.persisted? %>
      › <%= link_to_unless_current "Events", org_events_path(@org) %>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/orgs/_form.html.erb
<%= form_for(org) do |f| %>
  <% if org.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(org.errors.count, "error") %> prohibited this org from being saved:</h2>

      <ul>
      <% org.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orgs/edit.html.erb
<h1>Editing Org</h1>

<%= render 'form', org: @org %>

<%= link_to 'Back', orgs_path %>

app/views/orgs/index.html.erb
<h1>Orgs</h1>

<table>
  <tbody>
    <% @orgs.each do |org| %>
      <tr>
        <td><%= org.name %></td>
        <td><%= link_to 'Events', org_events_path(org) %></td>
        <td><%= link_to 'Edit', edit_org_path(org) %></td>
        <td><%= link_to 'Destroy', org, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Org', new_org_path %>

app/views/orgs/new.html.erb
<h1>New Org</h1>

<%= render 'form', org: @org %>

<%= link_to 'Back', orgs_path %>